version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    networks:
      - netschulz

  adminer:
    command: php -S 0.0.0.0:8080 -t /var/www/html
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - netschulz

networks:
  netschulz:
     driver: overlay

